apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: "1917234250249081394"
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/snackewm/emco
status: {}
