apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust2994916163060876980
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider1flux+cluster2/context/2994916163060876980
  prune: true
  sourceRef:
    kind: GitRepository
    name: "2994916163060876980"
  targetNamespace: default
status: {}
